# Generated by Django 5.2.3 on 2025-08-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada')], default='programada', max_length=20),
        ),
    ]
