# Generated by Django 5.2.3 on 2025-08-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0002_sesion_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesion',
            old_name='observaciones',
            new_name='comentario',
        ),
        migrations.AddField(
            model_name='sesion',
            name='motivo',
            field=models.CharField(choices=[('conductual', 'Conductual'), ('familiar', 'Familiar'), ('emocional', 'Emocional'), ('aprendizaje', 'Aprendizaje'), ('social', 'Social'), ('ansiedad', 'Ansiedad'), ('depresion', 'Depresión'), ('otro', 'Otro')], default='Sin comentarios', max_length=20),
            preserve_default=False,
        ),
    ]
