# Generated by Django 5.2.3 on 2025-08-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0003_rename_observaciones_sesion_comentario_sesion_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='motivo',
            field=models.CharField(choices=[('conductual', 'Conductual'), ('emocional', 'Emocional'), ('academico', 'Académico / Aprendizaje'), ('familiar', 'Familiar / Relaciones Familiares'), ('social', 'Social / Interacción con pares'), ('sueno', 'Trastornos del Sueño'), ('alimentacion', 'Trastornos de Alimentación'), ('desarrollo', 'Desarrollo / Habilidades')], max_length=20),
        ),
    ]
