# Generated by Django 5.2.3 on 2025-08-28 19:42

import pacientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='calle',
            field=models.CharField(default='Desconocida', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(default='Desconocida', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='comuna',
            field=models.CharField(default='Desconocida', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero',
            field=models.CharField(default='Desconocida', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='centro_educacional',
            field=models.CharField(choices=[('Arrayán', 'Colegio Arrayán'), ('Niños Felices', 'Colegio Niños Felices')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[pacientes.models.validar_rut]),
        ),
    ]
