# Generated by Django 5.2.3 on 2025-07-31 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Informe tipo 1 - Colegio'), ('2', 'Informe tipo 2 - Familia'), ('3', 'Informe en blanco')], max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contenido', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
