# Generated by Django 5.2.3 on 2025-08-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranza',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=40000, max_digits=10),
        ),
    ]
